networks:
  db_network:
    driver: bridge

volumes:
  db_data:


services:
  mongodb:
    container_name: parking-service-db
    image: mongo:7-jammy
    networks:
      - db_network
    volumes:
      - db_data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  parking_service:
    build:
      context: .
      dockerfile: src/docker/Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --workers 17
    ports:
      - "8000:8000"
    networks:
      - db_network
    depends_on:
      - mongodb
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
